<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU" Id="{b05d93c8-4a6b-4f07-aafd-3dcd31964579}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>